[directories]
data = "~/.local/share/virtman"
config = "~/.config/virtman"    # Where to search for additional config files
# Without -f <path>, virtman will first scan for a config file in "$XDG_CONFIG_HOME/virtman" (default "~/.config/virtman")
prefer_xdg = true # Whether to prefer XDG Base Directory environment variables or the directories defined in this config file
isos = "images"   # Where to store ISO files ($data/$isos)
mount = "mnt"     # Where to mount ISOs ($data/$mount)
disks = "disks"   # Where to store virutal disks ($data/$disks)

[[virtual_machines]]
name = "ubuntu"
reinstall = false                          # Whether to boot the install ISO and set appropriate boot parameters every time
command = "qemu-system-x86_64"             # As will be entered into a Bash shell by virtman
memory = "4G"                              # Allocated RAM
aio = "io_uring"                           # I/O interface (threads, native, or io_uring)
disk = "ubuntu.qcow"                       # Will be stored in ${directories[disks]}/$disk
format = "qcow2"                           # The format of the disk
size = "16G"                               # The size of the disk
iso = "ubuntu-24.04-live-server-amd64.iso" # Will match with the appropriate [[isos]] entry

[[isos]]
file_name = "ubuntu-24.04-live-server-amd64.iso"                                 # Will be stored in ${directories[isos]}/$file_name
url = "https://www.releases.ubuntu.com/noble/ubuntu-24.04-live-server-amd64.iso" # Direct links can be easily gotten from https://www.releases.ubuntu.com/
download = true                                                                  # Whether or not to download the ISO if the file does not already exist
force_redownload = false                                                         # Whether or not to download the ISO even if the file already exists
